on: [ push ]

name: WebDriver

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        webdriver-test: [ jest, webdriverio ]
    steps:
      - uses: actions/checkout@v2

      - name: Tauri dependencies
        run: >
          sudo apt-get update &&
          sudo apt-get install -y
            libgtk-3-dev
            libgtksourceview-3.0-dev
            webkit2gtk-4.0
            libappindicator3-dev
            webkit2gtk-driver
            xvfb

      - name: Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Yarn install
        run: yarn install
        working-directory: webdriver/

      - name: Install tauri-driver
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git "https://github.com/tauri-apps/tauri" --branch "feat/webdriver" tauri-driver

      - name: WebDriver
        run: xvfb-run yarn workspace ${{ matrix.webdriver-test }} test
        working-directory: webdriver/
