on: [ push ]

name: WebDriver

jobs:
  build_and_test:
    name: Hello Tauri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tauri dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgtksourceview-3.0-dev webkit2gtk-4.0 libappindicator3-dev webkit2gtk-driver

      - name: Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Yarn install
        run: yarn
        working-directory: webdriver/

      - name: Install tauri-driver
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git "https://github.com/tauri-apps/tauri" --branch "feat/webdriver" tauri-driver

      - name: Cache ~/.cargo/bin/
        uses: actions/cache@v2
        with:
          path: ~/.cargo/bin/
          key: ${{ runner.os }}-cargo-plugins

      - name: Start tauri-driver
        run: ~/.cargo/bin/tauri-driver &

      - name: Yarn test
        run: yarn test --runInBand
        working-directory: webdriver/
